[package]
name = "wei-file"
version = "0.1.2"
edition = "2021"

description = "wei file"
documentation = "https://github.com/zuiyue-com/wei-file"
homepage = "https://github.com/zuiyue-com/wei-file"
license = "MIT OR Apache-2.0"

[dependencies]
lzma-rs = "0.3.0"
tar = "0.4"